import * as THREE from "three";
import { NeonEnvironment } from "../game/neon-environment";
const canvas=document.getElementById("gantry-view") as HTMLCanvasElement;
const renderer=new THREE.WebGLRenderer({canvas,antialias:true});
renderer.setSize(1536,1024,false);renderer.outputColorSpace=THREE.SRGBColorSpace;
renderer.toneMapping=THREE.NoToneMapping;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x858980);scene.fog=new THREE.FogExp2(0x858980,.0028);
scene.add(new THREE.HemisphereLight(0xc9cebd,0x9a9686,2.8));
const key=new THREE.DirectionalLight(0xe2d8bd,2.1);key.position.set(-15,28,24);scene.add(key);
const camera=new THREE.PerspectiveCamera(34.2,1.5,.1,350);camera.position.set(4,2.4,74);camera.lookAt(0,9.5,0);
const model=await NeonEnvironment.load({rootName:"tidal_pump_review",modelUrl:"/assets/tideline-foundry/tidal-pump-gantry.glb",lightsUrl:"/assets/tideline-foundry/gantry-review-lights.json",colors:{GW_MAT_emissive:0xe9b36a},opticalEffects:false,maximumDistance:200,lightIntensity:65});
scene.add(model.root);
const texture=await new THREE.TextureLoader().loadAsync("/assets/tideline-foundry/textures/concrete.jpg");texture.colorSpace=THREE.SRGBColorSpace;texture.wrapS=texture.wrapT=THREE.RepeatWrapping;texture.anisotropy=4;
const floorGeometry=new THREE.PlaneGeometry(30,240,1,36);
const floorUv=floorGeometry.getAttribute("uv");
for(let i=0;i<floorUv.count;i++) floorUv.setXY(i, .512+floorUv.getX(i)*.476, .012+(Math.floor(i/2)%2)*.476);
const floor=new THREE.Mesh(floorGeometry,new THREE.MeshLambertMaterial({map:texture,color:0xffffff}));
floor.rotation.x=-Math.PI/2;floor.position.y=-.04;scene.add(floor);
const apronGeometry=new THREE.PlaneGeometry(180,240,12,36);
const apronUv=apronGeometry.getAttribute("uv");
for(let i=0;i<apronUv.count;i++) apronUv.setXY(i, .012+(i%2)*.476, .512+(Math.floor(i/13)%2)*.476);
const apron=new THREE.Mesh(apronGeometry,new THREE.MeshLambertMaterial({map:texture,color:0x797d6d}));
apron.rotation.x=-Math.PI/2;apron.position.y=-.1;scene.add(apron);
model.updateVisibility(camera);renderer.render(scene,camera);
document.getElementById("review-status")!.textContent=`READY · ${model.stats.triangles.toLocaleString()} triangles · ${model.stats.textures} painted atlases · no bloom`;
