"""Write the report from the instruments; never substitute hand-entered metrics."""
from pathlib import Path
import json,hashlib,subprocess,re,collections
out=Path('art/evidence/dreamisland-v1/polish');phase=out.parent/'phase-c'
def read(path):return json.loads(Path(path).read_text())
def j(name):return read(out/name)
def f(value,d=6):return f'{value:.{d}f}'
def link(label,path):return '['+label+']('+str(Path(path).resolve())+')'
old=j('baseline.json');head=subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip();assert head==old['head']
owned={'art/blender/build_dreamisland_heroes.py','art/blender/build_dreamisland_painted.py','art/blender/dreamisland_mesh.py','public/assets/dreamisland/painted.glb','public/assets/dreamisland/painted.json','public/assets/dreamisland/signage-manifest.json',*[f'src/game/dreamisland-{x}.ts' for x in ['painted-environment','materials','water','sky']]}
files=subprocess.check_output(['git','diff','--name-only'],text=True).splitlines()+subprocess.check_output(['git','ls-files','--others','--exclude-standard'],text=True).splitlines()
assert all(p in owned or p.startswith(('public/assets/dreamisland/heroes/','scripts/visual/dreamisland-heroes/','art/evidence/dreamisland-v1/polish/')) for p in files)
assert not subprocess.check_output(['git','diff','--name-only','HEAD','--','art/evidence/dreamisland-v1/phase-c','docs/briefs','art/references','scripts/validate*','src/game/data/dreamisland','src/game/dreamisland-course.ts','src/game/dreamisland-runtime.ts','src/game/dreamisland-schedule.js','src/game/dreamisland-powers.ts','src/game/dreamisland-powers-config.js'],text=True).strip()
code=j('test-code/test-code.json');assert code['exitCode']==0
for p,digest in code['verifiedSnapshotHashes'].items():assert hashlib.sha256(Path(p).read_bytes()).hexdigest()==digest,p
soaks={};reconciliations={}
for tier in ['works','rookie','feral','works-reduced']:
 m=j('soak-'+tier+'/metrics.json');r=j('soak-'+tier+'/race.json');walk=j('soak-'+tier+'/material-walk.json');c=r['diagnostics']['current'];assert c['missedGates']==0 and c['recoveries']==0 and not r['errors'] and not walk['violations']
 active=[x for x in r['frames'] if x['tick']>120];window=active[-720:];assert len(window)==m['windowSamples'];assert abs(sum(x['delta'] for x in window)-m['windowMs'])<1e-5;assert abs(m['windowSamples']-m['windowMs']/1000*m['calibration']['hz']-m['sampleResidual'])<1e-5
 assert m['peakTotalCalls']<=110 and m['peakTriangles']+m['peakShadowTriangles']<=180000
 reconciliations[tier]={k:m[k] for k in ['windowSamples','windowMs','calibration','expectedSamples','sampleResidual','p95Ms']};soaks[tier]={'metrics':m,'current':c,'violations':len(walk['violations'])}
feral=soaks['feral']['metrics'];assert feral['p95Ms']<=11;before=old['phaseCBaselineMetrics'];validation=j('test-code/validators/painted-validation.json');assert validation['corridor']['intrusions']==0 and validation['signage']['maximumLetterHeightMetres']<=.59
oldvalidation=read(phase/'validators/painted-validation.json');runtime=j('test-code/validators/runtime-validation.json');oldruntime=read(phase/'validators/runtime-validation.json');assert runtime['determinism']['identicalSnapshots']
oldwalk=read(phase/'soak-feral/material-walk.json');motion=j('waterfall-motion/motion.json');assert not motion['errors']
cross=j('crossfade-baseline/crossfade-acceptance.json');assert cross['checks']['road']['T1pass'];assert all(x[k] for x in cross['checks'].values() for k in ['T2pass','T3pass']);assert cross['checks']['sky']['withinTwoTimes']
baseline=j('crossfade-baseline/crossfade-profile.json');sea=j('crossfade-baseline/polish-profile.json')['blends'][0];oldsea=j('before/beach/polish-profile.json')['blends'][0];assert sea['seaLumaStd']>=.03 and sea['horizonMaximumStep']<.1
beach=baseline['blends'][-1];oldbeach=read(phase/'crossfade-shipped/crossfade-profile.json')['blends'][-1];pier=j('pier-edge/crossfade-profile.json')['blends'][-1];oldpier=read(phase/'pier-edge/after/crossfade-profile.json')['blends'][-1]
assert .12<=beach['road']['meanLuma']<=.18
assert beach['pierEdge']['contrast']>=oldbeach['pierEdge']['contrast'] and pier['pierEdge']['contrast']>=oldpier['pierEdge']['contrast']
kerb=j('kerb/kerb-profile.json');assert all(len(x['probes'])==2 and all(p['cyanWidthPixels']>=3 for p in x['probes'])for x in kerb['results'])
tunnel=j('tunnel/region-profile.json')['results'][0]['metrics'];assert tunnel['mouthToDrum']>=3
clock=j('clock-entry/region-profile.json')['results'][0]['metrics'];assert clock['clockface']['widthPixels']>=40 and clock['clockhands']['pixels']>0
waterfall=j('waterfall/region-profile.json');grove=j('grove/region-profile.json')['results'][0]['metrics']['foliage'];assert grove['columnCoverage']>=.25
canopy=j('canopy-clearance.json');assert canopy['additionalClearance']>=2
stacks=j('stacks/stack-profile.json')['results'][0];assert len(stacks['qualifyingPlacements'])>=2
loader=j('loader/loader-check.json');assert loader['assets']['watchtower']['bore']['intersectingTriangles']==0
focals=j('focals/focal-capture.json');assert len(focals['frames'])==16 and not focals['errors']
tints=j('focals/tint-profile.json');assert tints['chromaBetween']
other_tints=j('tint-calibration/tint-profile.json');palette=j('palette/palette.json');strike=j('strike/strike.json');assert len(strike['frames'])==10 and not strike['errors']
oldframes=read(phase/'frames/frames.json');frames=j('frames/frames.json');nearTriangles=frames['frames'][0]['painted']['waterTriangles']-oldframes['frames'][0]['painted']['waterTriangles'];assert len(frames['frames'])==14 and not frames['errors'] and not any(x.get('missed') for x in frames['frames'])
review=j('review-check.json');assert review['allImagesLoaded'] and review['playPauseWorks'] and not review['errors']
original_atlas=j('atlas-original-quadrant/atlas-quadrant-proof.json');added_atlas=j('atlas-added-quadrant/atlas-quadrant-proof.json');assert original_atlas['decided']==original_atlas['claims'] and added_atlas['decided']==added_atlas['claims']
painted=read('public/assets/dreamisland/painted.json');oldpainted=json.loads(subprocess.check_output(['git','show','HEAD:public/assets/dreamisland/painted.json'],text=True));count=lambda d:sum(p['asset']=='undergrowth-card-set' and p.get('sector') in ['GROVE','CUT'] for p in d['placements']);under=(count(painted)-count(oldpainted))*painted['assets']['undergrowth-card-set']['triangles']
text=(out/'README.md').read_text().split('UNVERIFIED (implementation and measurement pending)')[0].split('## Result and before/after frames')[0].rstrip()+'\n\n'
text+='## Result and before/after frames\n\nVERIFIED (`polish-report.py`, original instruments listed below): the nine residual checks and all mandatory automated gates pass. '+link('Open the review and strike flipbook',out/'index.html')+' · '+link('17-slot before/after sheet',out/'eyeball-before-after.png')+'.\n\n'
text+='| Original gap | BEFORE | AFTER |\n|---|---|---|\n'
for title,a,b in [('Sea / sky join',phase/'frames/day-beach.png',out/'frames/day-beach.png'),('Stone tower / moss',out/'before/watchtower/watchtower-40m-day.png',out/'focals/watchtower-40m-day.png'),('Night road / distant forms',phase/'frames/night-reef.png',out/'frames/night-reef.png'),('Canopy / verge / kerb',phase/'frames/day-grove.png',out/'frames/day-grove.png'),('Ramp pacing',phase/'crossfade-shipped/blend-075.png',out/'crossfade-baseline/blend-075.png')]:text+='| '+title+' | '+link('VERIFIED frame',a)+' | '+link('VERIFIED frame',b)+' |\n'
text+='\nVERIFIED (`polish-compose.py`): all seventeen source slots are paired on one sheet. The historical pier/shore BEFORE and AFTER slots used identical cameras; each corresponding new pair therefore reuses its fresh endpoint frame. Phase C stays untouched.\n\n## Files and asset checks\n\n'
text+='VERIFIED (`git diff --name-only`, `polish-report.py`): changes are confined to the owned Blender builders, hero assets, painted GLB/manifest, four Dream Island visual modules, review checks and polish evidence. Route, schedule, powers, pace, references, atlases, original validators and Phase C evidence are unchanged. HEAD remains `'+head[:7]+'`; no commit was made.\n\n'
text+='VERIFIED (Blender build logs; `check.mjs --out=.../polish/loader`): the watchtower uses stone-cell vertex moss, sparse keyed ivy, course joints and two lamps; the waterfall has full-drop sheet cards and a foam ring; the stacks use darker stone/cap tints. The clock GLB is unchanged and placed at the revised scale. All four GLBs load with shared `DI_MAT_<role>` names and no embedded textures.\n\n| Hero GLB | Triangles / asset ceiling | Exported bounds, metres | Evidence |\n|---|---:|---|---|\n'
spec=read('public/assets/dreamisland/heroes/heroes.json')['assets']
for name,a in loader['assets'].items():text+=f"| {name} | {a['triangles']:,} / {spec[name]['budget']:,} | "+' × '.join(f(v,3)for v in a['bounds']['size'])+' | VERIFIED (`loader/loader-check.json`) |\n'
text+='\nVERIFIED (loader anchors and painted validator): the waterfall sheet drop is '+f(loader['assets']['waterfall-cliff']['targetMeasurements']['drop'],3)+' m; the full AABB includes the cap above it. The clock source is 14 m and the live placement is '+f(14*next(p['scale'] for p in validation['heroes']['placements'] if p['asset']=='clock-tower'),3)+' m. The watchtower retains the accepted 1.10 runtime scale and its true arched clearance: rectangle to the spring line plus curved cap, with zero intersecting triangles.\n\n## Measured ceilings\n\n| Axis | Phase C record | Polish | Ceiling | Evidence |\n|---|---:|---:|---:|---|\n'
text+=f"| Total draws | {before['peakTotalCalls']} | {feral['peakTotalCalls']} | 110 | VERIFIED (`race.mjs --tier=feral`) |\n| Main + shadow triangles | {before['peakTriangles']+before['peakShadowTriangles']:,} | {feral['peakTriangles']+feral['peakShadowTriangles']:,} | 180,000 | VERIFIED (same metrics) |\n| p95 ms; sample residual | {f(before['p95Ms'],3)}; {f(before['sampleResidual'],3)} | {f(feral['p95Ms'],3)}; {f(feral['sampleResidual'],3)} | report; 11 ms target | VERIFIED (same metrics) |\n"
oldbuild=(phase/'validators/test-code.log').read_text();oldinitial=re.findall(r'([\d.]+) KiB gzip initial JS',oldbuild)[-1];oldshell=re.findall(r'([\d.]+) KiB gzip shell',oldbuild)[-1]
build=(out/'build-final.log').read_text();shell=re.findall(r'([\d.]+) KiB gzip shell',build)[-1];initial=re.findall(r'([\d.]+) KiB gzip initial JS',build)[-1]
assert float(initial)<=266 and float(shell)<=277
text+=f"| Initial JS / shell gzip, KiB | {oldinitial} / {oldshell} | {initial} / {shell} | 266 / 277 | VERIFIED (`npx vite build && node scripts/validate-build.mjs`) |\n| Corridor intrusions | {oldvalidation['corridor']['intrusions']} | {validation['corridor']['intrusions']} | 0 | VERIFIED (`validate:dreamisland-painted`) |\n| Material-walk violations | {len(oldwalk['violations'])} | {sum(s['violations'] for s in soaks.values())} | 0 | VERIFIED (all four `race.mjs` walks) |\n| Maximum letter height, m | {f(oldvalidation['signage']['maximumLetterHeightMetres'],4)} | {f(validation['signage']['maximumLetterHeightMetres'],4)} | 0.59 | VERIFIED (painted validator glyph fractions) |\n| Determinism | {' / '.join(map(str,oldruntime['determinism']['renderRates']))} Hz identical={oldruntime['determinism']['identicalSnapshots']} | {' / '.join(map(str,runtime['determinism']['renderRates']))} Hz identical={runtime['determinism']['identicalSnapshots']} | identical | VERIFIED (`validate:dreamisland-runtime`) |\n| Atlas decisions | {original_atlas['claims']} / {original_atlas['claims']} | {original_atlas['decided']+added_atlas['decided']} / {original_atlas['claims']+added_atlas['claims']} | every consumer | VERIFIED (original + added quadrant-ID probes) |\n"
text+='\nVERIFIED (`soak-feral/metrics.json`, wrapped shadow pass):\n\n| Lighting state | Main / shadow draws | Main / shadow triangles |\n|---|---:|---:|\n'
for state,m in feral['lightingStates'].items():
 if isinstance(m,dict):text+=f"| {state} | {m['peakMainCalls']} / {m['peakShadowCalls']} | {m['peakTriangles']:,} / {m['peakShadowTriangles']:,} |\n"
text+='\n## Ordered residual measurements\n\n'
text+=f"1. VERIFIED (`crossfade-profile` + `polish-profile.py`): sea luma standard deviation {f(oldsea['seaLumaStd'])} → {f(sea['seaLumaStd'])}; mean horizon step {f(oldsea['horizonMeanStep'])} → {f(sea['horizonMeanStep'])}, maximum {f(sea['horizonMaximumStep'])}. The near patch adds {nearTriangles:,} triangles in the existing sea draw (district-frame water counters before/after).\n"
m=tints['measurements'];text+='2. VERIFIED (`polish-tint.py`, shared-light 40 m frame): lower-band chroma, neutral stone / original moss / polish = '+ ' / '.join(f(m[k]['meanChroma'])for k in ['neutralStone','originalMoss','polishedTint'])+'. Corresponding luma = '+' / '.join(f(m[k]['meanLuma'])for k in ['neutralStone','originalMoss','polishedTint'])+f". The POINT approach mouth/drum ratio is {f(tunnel['mouthToDrum'])}.\n"
text+='3. VERIFIED (`polish-kerb.py`): cyan stripe widths at exactly 40 m = '+ '; '.join(('night' if r['blend'] else 'day')+' '+ '/'.join(str(p['cyanWidthPixels'])for p in r['probes'])+' px' for r in kerb['results'])+'. Real top faces have upward normals; the mesh receives shadows; the inner boundary is retained. The new shoulder uses the existing concrete batch.\n'
text+=f"4. VERIFIED (`polish-canopy.mjs`, `polish-regions.py`, manifests): foliage covers {grove['columnsAboveHorizon']}/{grove['frameColumns']} columns above the GROVE horizon ({grove['columnCoverage']:.1%}); minimum canopy clearance above the corridor ceiling is {f(canopy['additionalClearance'])} m. GROVE/CUT understory placements {count(oldpainted)} → {count(painted)}, adding {under:,} triangles ({under/32000:.1%} of the brief’s 32k reserve) in the existing batch. Painted GLB total {oldpainted['triangles']:,} → {painted['triangles']:,}, with {oldpainted['meshes']} → {painted['meshes']} material batches.\n"
text+=f"5. VERIFIED (original crossfade instrument, matched cameras): BEACH night road luma {f(oldbeach['road']['meanLuma'])} → {f(beach['road']['meanLuma'])}; BEACH edge contrast {f(oldbeach['pierEdge']['contrast'])} → {f(beach['pierEdge']['contrast'])}; REEF edge contrast at the Phase C .72 pose {f(oldpier['pierEdge']['contrast'])} → {f(pier['pierEdge']['contrast'])}.\n"
text+=f"6. VERIFIED (`polish-crossfade-check.py`): maximum/minimum sky step ratio {f(cross['checks']['sky']['stepRatio'])}; T1 road midpoint deviation {f(cross['checks']['road']['T1midpointDeviation'])}; T2 and T3 pass.\n"
text+=f"7. VERIFIED (`polish-regions.py`): COURT-entry face {clock['clockface']['widthPixels']} × {clock['clockface']['heightPixels']} px, with {clock['clockhands']['pixels']} visible hand pixels. The waterfall’s shared-water sheet and foam are visible in both lighting states; its animation clock advances normally and stays zero under reduced motion.\n"
text+='8. VERIFIED (`polish-stacks.py`): qualifying REEF silhouettes = '+str(len(stacks['qualifyingPlacements']))+'; '+ '; '.join(f"{c['placement']['child']} at {f(c['placement']['distance'],3)} m, contrast {f(c['silhouetteContrast'])}" for c in stacks['components'] if c['placement']['index'] in stacks['qualifyingPlacements'])+'.\n'
text+='9. VERIFIED (`polish-horizons.py`, four day frames): the panorama samples above the measured painted shoreline; the second panorama horizon is gone. Full-frame and isolated-dome row profiles are recorded in `horizon-row-profiles.json`. Occluded sea/sky boundaries remain null rather than being reported as zero.\n\n'
text+='VERIFIED (`polish-focals.mjs`): sixteen 40 m / 300 m day/night focal frames, gathered in `focals/contact-sheet.png`, use the game’s shared lighting, fog and tone mapping. The clock uses its revised placed scale; other review assets retain source metres, with the larger accepted watchtower runtime placement checked separately. VERIFIED (`frames.mjs`): fourteen district frames provide both-state verge/card evidence in `frames/verge-contact-sheet.png`.\n\n'
text+='## Ten means: preserved BEFORE, new baseline, independent repeat\n\nVERIFIED (unchanged `crossfade-profile.mjs` + `.py`, then `polish-crossfade-check.py`): same camera and five blend values. T1 uses the new endpoints; T2 checks both regions; T3 checks the new baseline against the independent repeat.\n\n'+(out/'crossfade-baseline/ten-means.md').read_text()+'\n'
text+='## Palette and tint calibration\n\nVERIFIED (`polish-palette.py`): eight Pillow median-cut dominants from each half of `08_the_strike.png` and each complete HUD-free BEACH endpoint. Different compositions change proportions. The road is neutral by day and grey at night, with the cyan water cue preserved. The full-frame dominant lists still differ: the game’s large road area weights greys and dark greens, while the reference weights more pale blue by day and warm stone at night. This is a palette comparison, not a claim of identical gamut or composition.\n\n| Frame | Eight dominant colours, in pixel-share order |\n|---|---|\n'
for name,values in palette['palettes'].items():text+='| '+name+' | '+', '.join(v['hex']+f" ({v['pixelShare']:.1%})"for v in values)+' |\n'
text+='\nVERIFIED (`tint-calibration/tint-profile.json`): additional rendered-luma calibrations at the recorded poses:\n\n| Consumer | Mean luma | Mean chroma |\n|---|---:|---:|\n'
for item in other_tints['results']:
 for name,m in item['metrics'].items():text+=f"| {item['name']} / {name} | {f(m['meanLuma'])} | {f(m['meanChroma'])} |\n"
text+='\nVERIFIED (`waterfall/region-profile.json`):\n\n| Waterfall region / state | Visible pixels | Mean luma |\n|---|---:|---:|\n'
for result in waterfall['results']:
 for region,m in result['metrics'].items():text+=f"| {region} / "+('night' if result['blend'] else 'day')+f" | {m['pixels']} | {f(m['meanLuma'])} |\n"
pixelmotion=j('waterfall-motion/pixel-motion.json')
text+='\nVERIFIED (`polish-motion.mjs`, `waterfall-motion/motion.json`): reduced-motion sheet UV time remains '+str(next(r['uniforms'] for r in pixelmotion if r['reduced']))+' and emissive intensity remains '+str(next(r['emissive'] for r in pixelmotion if r['reduced']))+'. The shared lighting is still active; the isolated reduced-motion frames are not pixel-identical ('+str(next(r['changedPixelsAboveTwoLevels'] for r in pixelmotion if r['reduced']))+' pixels differ by more than two display levels). This verifies parked UV motion and constant emission, not a frozen rendered frame.\n'
text+='\n## Soaks, suite and rendered atlas checks\n\nVERIFIED (original `race.mjs` + `instrument.mjs`):\n\n| Tier | Lap times, ms | Missed / recoveries | Draws | Main + shadow triangles | p95 ms | Sample residual |\n|---|---|---|---:|---:|---:|---:|\n'
for tier,s in soaks.items():
 m=s['metrics'];c=s['current'];text+=f"| {tier} | "+' / '.join(map(str,c['lapTimesMs']))+f" | {c['missedGates']} / {c['recoveries']} | {m['peakTotalCalls']} | {m['peakTriangles']+m['peakShadowTriangles']:,} | {f(m['p95Ms'],3)} | {f(m['sampleResidual'],3)} |\n"
text+='\nVERIFIED (`polish-report.py`): sampled intervals, expected samples and residuals in `sample-reconciliation.json` reconcile exactly with the original frame records. Timing is a local 1280×720 ANGLE/Metal result. All material walks and browser error lists are clean.\n\n'
text+='VERIFIED (`test-code/test-code.json`): unchanged `npm run test:code` passes on a byte-checked temporary snapshot. Its original evidence-writing defaults stay inside that snapshot; read-only Git index access supports the unchanged security/soundtrack checks. Source hashes are rechecked against this final tree.\n\n'
text+='VERIFIED (`atlas-original`, `atlas-added`, both quadrant-ID directories): the original fourteen and nine added consumers are rendered against their source cells and unambiguous quadrant colours. '+link('Atlas contact sheet',out/'atlas-cells.png')+'. `palette-attribute-proof.json` proves the final shoulder tint edit left every index, position, normal and UV unchanged; the quadrant probes deliberately disable vertex colours.\n\n'
text+='## Commands and report limits\n\nVERIFIED (command logs and source hashes): the named original visual scripts run through `node scripts/visual/dreamisland-heroes/polish-run.mjs SCRIPT ...`, with `TIDELINE_PUPPETEER` pointing to `polish-transport.mjs`. This wrapper bounds browser cleanup and exits after the instrument finishes. For `race.mjs` only, its hard-coded port 5200 is redirected to this task’s private 5217 server; `transport.json` records both URLs. No rendering, physics, timing algorithm or validator assertion changes.\n\n'
text+='VERIFIED (scope audit): no AI image, texture or 3D generator was used. Geometry was authored in Blender/Python; evidence is rendered geometry, direct pixel measurement, and labelled composites. No commits.\n\n'
text+='VERIFIED (discrepancies): the baseline sea variation and GROVE coverage already exceeded the brief’s rough estimates; the report uses the measured BEFORE values. The clock source remains 14 m while its placement is 18 m. The full waterfall AABB is taller than its exact 16 m sheet drop. POINT contact-sheet cameras are inside the tunnel, so the mouth ratio uses the recorded .32 approach. The original material walk exempts its two existing sky names. The original colour-equality masks retain their recorded overlap counts; no mean or assertion was edited to hide that measurement limit.\n\n'
text+='VERIFIED (source discrepancies): [handoff:18]('+str(Path('docs/briefs/DREAM-ISLAND-HANDOFF.md').resolve())+':18) quotes a different reviewer residual. The BEFORE timing column uses the committed `phase-c/soak-feral/metrics.json`, and [race.mjs:48]('+str(Path('scripts/visual/dreamisland/race.mjs').resolve())+':48) is the unchanged two-name sky exemption.\n\n'
text+='VERIFIED (`strike/strike.json`): the final strike sequence is '+link('here',out/'strike')+'; the local '+link('flipbook',out/'index.html')+' (images, slider and playback verified by `polish-review-check.mjs`) lets the reviewer step through all ten frames.\n\nUNVERIFIED (requires the user’s visual judgement): final art acceptance. All requested builds, measurements, the suite and four soaks are recorded above.\n'
(out/'README.md').write_text(text)
summary={'head':head,'changedFiles':files,'feral':{k:feral[k] for k in ['peakTotalCalls','peakTriangles','peakShadowTriangles','p95Ms','sampleResidual']},'checks':'All named assertions in this report passed','sourceHashes':{p:hashlib.sha256(Path(p).read_bytes()).hexdigest() for p in files if not p.startswith('art/evidence/') and Path(p).is_file()},'suiteSourceHashMatches':len(code['verifiedSnapshotHashes']),'noCommit':True}
(out/'sample-reconciliation.json').write_text(json.dumps(reconciliations,indent=2)+'\n')
(out/'final-verification.json').write_text(json.dumps(summary,indent=2)+'\n');print('VERIFIED final report and scope audit')
