import { chromium } from "playwright";
const [url, out, waitMs] = [process.argv[2], process.argv[3], Number(process.argv[4] || 6000)];
const browser = await chromium.launch({ args: ["--use-angle=metal", "--enable-gpu", "--ignore-gpu-blocklist"] });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
page.on("pageerror", (e) => console.log("[pageerror]", String(e).slice(0, 200)));
await page.goto(url, { waitUntil: "networkidle" });
await page.waitForTimeout(waitMs);
await page.screenshot({ path: out });
const d = await page.evaluate(() => { try { const c = JSON.parse(document.getElementById("futurisma-diagnostics")?.textContent || "{}").current || {}; return { d: c.distanceMeters, lat: c.lateralMeters, v: c.speedKph, sector: c.sector, phase: c.phase, probe: c.probe, apron: c.onApron, edge: c.edgeSeconds }; } catch { return null; } });
console.log(JSON.stringify(d));
await browser.close();
