"""Generate the §8 report from measured files; retain failed gates explicitly."""
from pathlib import Path
import json
root=Path.cwd();e=root/'art/evidence/dreamisland-v1/alive/3d';out=e/'review-8'
proof=json.loads((out/'proof.json').read_text());old=json.loads((e/'step-0/review-measurements.json').read_text())
final=json.loads((out/'step-4/review-measurements.json').read_text());bound=json.loads((out/'cap-probe/bound.json').read_text())
lines=['# §8 water revision — uncommitted','', '**REQUEST CHANGES remains open:** the literal white-glint gate is incompatible with the specified cap and the COURT sun/view geometry. The shader keeps the 1.0 clamp, ≤8° normals, existing sun, tone mapping and fog. No git commit was made. The accepted §5.2–§5.6 implementation is unchanged.','',
'## Constraints and implementation','',
'- Sky response is multiplied by the sampled atlas colour and its normalized hue. This extra pigment tint restores the sea chroma margin spent by the bounded glint. Schlick F0 is 0.02; reflection weight is 0.14 at grazing and 0.0028 at normal incidence, below both corrected caps.',
'- Four differently directed waves use frequency magnitudes near √½, √2, √3 and √5. Their gradient has a hard norm bound below 0.14: tilt stays below 8°. Blinn exponent 64, gain 4, clamped to 1.0 per colour channel. No texture, triangle or draw is added.',
'- Wet road uses the smooth geometry normal without perturbation, exponent 8, and a fixed cyan lamp direction. A vertex flag from the existing atlas quadrant excludes all kerb triangles, even though kerbs and road share one material/draw.',
'- Night sea keeps the requested dark tint. Shallows/foam emission is 12/18 × nightBlend within 80 m, rising smoothly to 64/96 at 160 m. The distant boost preserves the COURT sources through fog while reducing nearby REEF clipping. This is an art-directed distance response, not physical light transport; fog and tone mapping still run normally. The road term stays small. Source-disabled captures suppress only water emission while retaining geometry, diffuse shading, road, camera and sky.',
'', '## Measurement method','',
'Brief: `9d7f744`, `work/dream-island-alive`. Captures use the isolated `eafe0b9` tree plus F-3D resources, retaining the accepted AO and excluding concurrent F-CODE work. The documentation-only difference from 9d7f744 does not alter the renderer. Stage 0 retains accepted AO; the original step-0 sea/road pixels are still the numeric reference. Step 3 replays the accepted depth band without revising it.',
'',
'1280×720, Works, seed 3868938316, COURT .575 / REEF .75, fixed shipped chase pose. `measure.py` still invokes the unchanged grade instrument. The whole-frame columns mean its existing HUD-excluded world band (x 30–97%, y 18–62%). Sea uses exact visible `-sea` isolation pixels inside that same band. Road uses the original exact visible `-road` mask within x 40–75%, y 48–85%. White is BT.709 luma >239; components use eight-neighbour connectivity. FFT is zero-padded (no wraparound), normalized at zero lag, and tests local secondary peaks rather than adjacent samples in the central lobe. An empty white mask scores zero but does **not** satisfy the required white coverage.',
'',
f'The painting is resized once with Lanczos to 1280×720, then sampled with the identical COURT road mask: **painting road p99 = {proof["paintingRoadP99"]:.2f}** (p50 32.14). This is a screen-coordinate comparison, not a claim that the generated painting preserves every road boundary. The original §2 rows and framing caveat remain in the parent report. No REEF painting was supplied.',
'', '## Ordered table','',
'Each stage captures both states at both poses and runs both measurement scripts before the next stage is installed. `first-replay/` preserves the insufficient sea-tint trial; the table below is the corrected replay. “AC” is the largest normalized secondary autocorrelation peak.',
'',
'| Step | Pose/state | World mean | Std | Chroma | p99 | Range | Sea chroma | Sea p50 | Sea white % | Max blob px | Sea AC | Road p50 | Road p99 / painting | Road white % | Road AC |',
'|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|']
for stage in range(5):
 for row in json.loads((out/f'step-{stage}/review-measurements.json').read_text()):
  sea,road=row['sea'],row['road'];state='day' if row['blend']=='000' else 'night'
  painting=f'{proof["paintingRoadP99"]:.2f}' if row['pose']=='court' and state=='night' else '—'
  values=[str(stage),row['pose']+' '+state,*[f'{row[k]:.2f}' for k in ['lumaMean','lumaStd','chromaMean','p99','range']],f'{sea["chroma"]:.3f}',f'{sea["p50"]:.2f}',f'{sea["whitePct"]:.3f}',str(sea['maxWhiteBlob']),f'{sea["autocorrelationPeak"]:.3f}',f'{road["p50"]:.2f}',f'{road["p99"]:.2f} / {painting}',f'{road["whitePct"]:.3f}',f'{road["autocorrelationPeak"]:.3f}']
  lines.append('| '+' | '.join(values)+' |')
lines+=['','## Reference deltas','','| COURT state/source | Mean | Std | Chroma | p99 | Range | Black % | White % |','|---|---:|---:|---:|---:|---:|---:|---:|']
references={
 '000': [('§2 shipped',[132.9,52.7,19.0,207.3,190.0,.35,0]),('painting',[117.2,47.3,22.1,219.2,192.0,.41,.35])],
 '100': [('§2 shipped',[30.4,18.1,10.7,79.1,75.6,23.3,0]),('painting',[31.0,34.9,8.9,193.5,191.5,38.9,.06])]}
for blend in ['000','100']:
 row=next(r for r in final if r['pose']=='court' and r['blend']==blend)
 comparison=references[blend][:1]+[('revised',[row[k] for k in ['lumaMean','lumaStd','chromaMean','p99','range','blackPct','whitePct']])]+references[blend][1:]
 for label,values in comparison:lines.append('| '+('day' if blend=='000' else 'night')+' '+label+' | '+' | '.join(f'{v:.2f}' for v in values)+' |')
lines+=['','Full grade outputs (including p01, black %, white % and no-sky results) are in each stage’s `measurements.json`; isolation metrics and mask images are beside them.','', '## Literal gate results','']
for row in proof['gates']:
 failed=[name for name,passed in row['checks'].items() if not passed]
 lines.append(f'- {row["pose"]} {"day" if row["blend"]=="000" else "night"}: '+('PASS all listed checks.' if not failed else '**UNMET:** '+', '.join(failed)+'.'))
lines+=['',f'The cap diagnostic applies a glint of 1.0 to every water fragment: sea maximum {bound["seaMaximumLuma"]:.2f}, p99 {bound["p99"]:.2f}, white coverage {bound["seaWhitePct"]:.2f}%. It cannot cross 239 even when sparsity is abandoned. `sun-cone-bound.json` independently finds the closest COURT sun half-vector needs a 60.56° normal tilt; the allowed cone is 8°. These are constraints on the requested gate, not a justification to claim it passed.',
'', 'REEF’s original whole-frame day chroma is 17.58, already below the literal 21.8 floor. The table reports that floor honestly at both poses; it does not silently substitute a different REEF threshold.','', '## Sky, rails and source attribution','','All eight sky comparisons are pixel-identical, including the original step-0 sky. Both night rail isolations and the REEF day rail isolation are pixel-identical. COURT day has one changed pixel at (367,387): RGB (122,122,100) → (123,122,100), also inside the attached rail crop. The strict gate table leaves that daytime rail check unmet; no tolerance is silently substituted. Full results are in `proof.json`.','', '| Pose | Night p99 with sources | Range with sources | p99 without water emission | Range without water emission |','|---|---:|---:|---:|---:|']
for row in proof['emission']:
 a,b=row['withEmission'],row['withoutWaterEmission'];lines.append(f'| {row["pose"]} | {a["p99"]} | {a["range"]} | {b["p99"]} | {b["range"]} |')
lines+=['', 'The isolated tree has no §4 bollards or capsule placements; this source test attributes the rise to foam/shallows. It makes no claim about combined gameplay or the accepted glow’s contribution.','', '## Crops','', 'Each sea crop is the original 400×200 rectangle at (0,260), enlarged 2× with nearest-neighbour sampling. It includes the sea strip and adjacent sky/shore because the chase pose does not contain a contiguous 400×200 rectangle of only water. It is a visual context crop, distinct from the world-band metric mask.','', 'Before:','', '![Before sea, 2×](step-0/court/blend-000-sea-2x.png)','', 'Revised:','', '![Revised sea, 2×](step-4/court/blend-000-sea-2x.png)','', 'Night road:','', '![Night road](step-4/court/blend-100.png)','', 'Rails, isolated crop (400×200 at 90,325, enlarged 2×):','', '![Unchanged rails](step-4/court/blend-100-rails-2x.png)','', 'REEF night still has 0.98% whole-frame white coverage (down from 6.08% in the rejected uniform-emission trial); this remaining source brightness is a visual tradeoff, not an additional passed gate.','', '![REEF night](step-4/reef/blend-100.png)','', 'Updated eight-colour atlas-water comparison:','', '![Water palette](water-palettes.png)','', '## Performance and validation','']
for label in ['baseline','works','rookie','feral','works-reduced']:
 path=out/f'soak-{label}'/'metrics.json'
 if path.exists():
  m=json.loads(path.read_text());lines.append(f'- {label}: {m["peakTotalCalls"]} draws; {m["peakTriangles"]+m["peakShadowTriangles"]} main+shadow triangles; p95 {m["p95Ms"]:.2f} ms; residual {m["sampleResidual"]:+.3f}.')
if (out/'soak-baseline/metrics.json').exists() and (out/'soak-works/metrics.json').exists():
 a=json.loads((out/'soak-baseline/metrics.json').read_text());b=json.loads((out/'soak-works/metrics.json').read_text());lines.append(f'\nMatched Works delta: {b["p95Ms"]-a["p95Ms"]:+.2f} ms. Control retains accepted AO, glow and final emission levels; water/road reflection, glint and the new emission-distance hook are disabled. No F-3D browser captures overlap the timed runs; concurrent work elsewhere on this shared host is uncontrolled.')
build=json.loads((out/'build-size.json').read_text());prior=json.loads((e/'build-size.json').read_text())
lines+=[f'\nBuild and type check, build ceilings, runtime determinism and painted/corridor validation all pass (`validation.json`). Shell gzip: {build["shellGzip"]:,} B ({build["shellGzip"]/1024:.2f} KiB), below 277.5 KiB. Named island lazy JS: {build["islandGzip"]:,} B, below the prior isolated allowance of {prior["islandCeiling"]:,} B (prior measurement {prior["islandGzip"]:,} B + 10%). This does not validate the combined F-CODE JS/CSS pin.']
lines+=['','PMREM CPU submission costs (not GPU timer measurements):','']
for pose in ['court','reef']:
 c=json.loads((out/'step-4'/pose/'crossfade-capture.json').read_text())
 for capture in c['captures']:lines.append(f'- {pose}, blend {capture["blend"]}: {capture["applied"]["reflections"]["pmremCpuMs"]:.2f} ms; two 128-face PMREM captures, once per scene load.')
lines+=['','Accepted recipe/glow tail unchanged: '+str(proof['acceptedRecipesAndGlowUnchanged'])+'. Build/type and material-walk evidence are stored alongside the timed runs. Combined F-CODE integration remains outside this isolated validation.','', '## Commands','', 'Run from the project root unless stated otherwise:','', '```sh','python3 art/evidence/dreamisland-v1/alive/3d/prepare-review.py','node node_modules/vite/bin/vite.js --host 127.0.0.1 --port 5204 # in the isolated tree','python3 art/evidence/dreamisland-v1/alive/3d/ordered-review.py 0 4','python3 art/evidence/dreamisland-v1/alive/3d/review-proof.py','python3 art/evidence/dreamisland-v1/alive/3d/cap-probe.py','python3 art/evidence/dreamisland-v1/alive/3d/sun-cone-bound.py','python3 art/evidence/dreamisland-v1/alive/3d/review-validate.py','python3 art/evidence/dreamisland-v1/alive/3d/review-soaks.py','python3 art/evidence/dreamisland-v1/alive/3d/review-soak-proof.py','python3 art/evidence/dreamisland-v1/alive/3d/palette.py review-8/step-4 review-8','python3 art/evidence/dreamisland-v1/alive/3d/review-report.py','```','', '`ordered-review.py` expands the exact capture, grade and isolation commands into sequential stages. Stage source snapshots and served-file hashes are retained. The 64/96 everywhere trial in `night-wide-emission/` passed range but produced 6.08% whole-frame white at REEF; it was rejected visually. `night-foam-trial/` preserved nearby shallows but missed COURT range. The final distance response addresses that tradeoff. The cap probe replaces only the bounded glint expression with `1.` in the isolated tree for one capture, then restores it. `autocorrelation.py` is added beside `measure.py`; it is deliberately uncommitted, following “Commit nothing.”','', '## Numbers first measured in this revision','', 'Sea-band chroma and median against step 0; eight-connected white blob area; normalized secondary autocorrelation; painting road-band p99; road-band percentiles and white fraction; normal-cone geometric bound; everywhere-at-cap glint bound; exact rail-isolation differences; water-emission-disabled night range; matched new shader performance delta.']
(out/'README.md').write_text('\n'.join(lines)+'\n')
