"""Build a reviewable side-by-side index without altering either source image."""
from pathlib import Path
import json,html,hashlib
root=Path('art/evidence/ascension-v1/phase-b');build=json.loads((root/'model-build.json').read_text());records=[];sections=[];assessment={r['asset']:r for r in json.loads((root/'focal/assessment.json').read_text())['records']}
for asset in ['rocket-platform','crawler-transporter','countdown-board','trench-wall-module','deluge-water-tower','propellant-tank','vent-stack','crawlerway-gravel-bed','mangrove-pier','egret-card-set','service-tower-swing-arm']:
 model=root/'focal'/(asset+'.png');hero=Path('art/references/ascension')/('hero-'+asset+('-flux2.png' if asset in ['rocket-platform','crawler-transporter','countdown-board','trench-wall-module'] else '-gptimage2.png'))
 row={'asset':asset,'hero':str(hero),'model':str(model),'heroSha256':hashlib.sha256(hero.read_bytes()).hexdigest(),'modelSha256':hashlib.sha256(model.read_bytes()).hexdigest(),'authoredDetailsToReview':build['features'][asset],'assessment':assessment[asset]};records.append(row)
 items=''.join('<li>'+html.escape(detail)+'</li>' for detail in row['authoredDetailsToReview'])
 sections.append('<section id="'+asset+'"><h2>'+asset.replace('-',' ').title()+'</h2><div class="pair"><figure><img src="../../../../references/ascension/'+hero.name+'"><figcaption>Reference hero</figcaption></figure><figure><img src="'+model.name+'"><figcaption>Authored model · shared dawn lighting and fog · camera height 2.4 m</figcaption></figure></div><ul>'+items+'</ul><p>'+html.escape(assessment[asset]['status'])+': '+html.escape(assessment[asset]['gap'])+'</p></section>')
page='<!doctype html><meta charset="utf-8"><title>Ascension focal asset review</title><style>body{background:#242820;color:#e4e3d4;font:16px system-ui;margin:32px}section{padding:20px 0;border-top:1px solid #666}.pair{display:grid;grid-template-columns:1fr 1fr;gap:16px}figure{margin:0}img{width:100%;height:440px;object-fit:contain;background:#171b15}figcaption{margin-top:8px;color:#c8c3a5}li{margin:4px}</style><h1>Ascension Pad · focal review</h1><p>Working comparisons. The list beneath each pair is the authored feature checklist; approval requires the visual match.</p>'+''.join(sections)
(root/'focal/review.html').write_text(page);(root/'focal/review.json').write_text(json.dumps({'script':'scripts/visual/ascension/focal-review.py','records':records},indent=2))
