"""Write the repair report from completed evidence; no performance numbers are typed."""
import json,subprocess,hashlib
from pathlib import Path
root=Path('art/evidence/ascension-v1/phase-b-revision')
r=json.loads((root/'reconciliation.json').read_text());runs=r['runs'];zones=json.loads(Path('public/assets/ascension/trench-zones.json').read_text());floors=json.loads((root/'road-luma-floor.json').read_text())
locked=['src/game/data/ascension/route.json','src/game/data/ascension/schedule.json']
driving=json.loads((root/'driving.json').read_text())
preserved={p:Path(p).read_bytes()==subprocess.check_output(['git','show','2ebd9d5:'+p]) for p in locked}
lines=['# Ascension Pad — Phase B repair submission','','**Phase C has not started. Independent visual acceptance remains pending.** The five repair implementations are submitted for review; this document does not declare Phase B accepted.','', '## Executed and observed','', '- Replaced canopy slabs with Greenwater alpha canopy cards, thin trunks and root fans. The exact source texture and extraction are recorded in `fix-1/provenance.json`. Final station and board captures are in `stations/`. Canopy top is authored at 8.9 m, trunk diameter 0.4 m (`src/game/ascension-mangroves.ts`); this is geometry specification, not a timed measurement. Both final board camera distances are recorded by `scripts/visual/ascension/review.ts`, at 150 m. The older repair-one captures used a longer approach; those files are retained and superseded for the exact-distance check.','- Rebuilt the platform and crawler. `fix-2/geometry.json`, produced by `scripts/validate-ascension-heroes.mjs`, measures four exported tread units at 12 m long and 4 m tall, and records three swing-arm roots. `fix-2/comparison.html` and `fix-2/review.json` give reference comparisons and five proposed shared details per asset. Maquettes were removed before export; structural validation does not establish visual fidelity.','- Authored four contiguous trench zones. The route is unchanged. The ten evenly spaced tour anchors are retained, plus three boundary anchors; transition cameras sit 32 m before the boundary so both sides appear in one frame. `trench-tour/` holds the thirteen final no-HUD captures (`scripts/visual/ascension/stations.mjs`).','', '| Zone | Measured length, m |','|---|---:|']
for z in zones['zones']:lines.append(f"| {z['name']} | {z['lengthMetres']:.3f} |")
lines+=['', 'Zone lengths above come from `art/blender/ascension_trench.py`, summing the accepted shortcut centreline. They are spatial measurements, not timed samples.','', '- Added painted mud, grass and gravel within the existing water-role atlas, with shaped land and continuous road shoulders. The built-in image generator produced `ground-water-atlas-v2.png`; exact prompt and artifact ID are in `art/references/ascension/generation.json`. It did not expose a service job ID. `src/game/ascension-terrain.ts` retains Tideline wave/flow equations under shared Lambert lighting, fog and tone mapping, with a subdued ripple highlight and a mask excluding baseline water from the excavated trench.','- Instanced mangroves, kerbs, recessed deck lamps, street lamps and repeated trench walls; frustum selection occurs before filling visible instance batches. Distant wall LODs begin beyond 160 m; the close modules remain unchanged. Static world props and board housings share a paint shader that retains their individual atlases (`ascension-instance-lamps.ts`, `ascension-static-paint.ts`, Blender build script). Rejected experiments remain in `fix-5/` and `experiment-ledger.json`.','- Road-luma base was recorded first with `record-road-base.py`, then floors pinned with the unchanged formula in `pin-road-floor.py`. Original blockout and previous painted base/floor pairs remain in `phase-a/` and `phase-b/`; the new pair is here. These floors do not certify future steam or launch lighting.','', '## Completed race measurements','', 'All race figures below use `scripts/visual/ascension/race.mjs` and `instrument.mjs`, on the protocol in `fix-5/protocol.json`. No imported runtime or art was changed during a measured race. Main/shadow peaks are independent; total peak is measured per frame.','', '| Run | Lap times, ms | Peak main / shadow / total draws | Peak main triangles | Tail p95, ms |','|---|---|---:|---:|---:|']
for x in runs[:4]:lines.append(f"| {x['directory']} | {', '.join(map(str,x['lapTimesMs']))} | {x['peakMainDraws']} / {x['peakShadowDraws']} / {x['peakTotalDraws']} | {x['peakMainTriangles']:,} | {x['p95Ms']:.2f} |")
lines+=['', f"Final budget gate passed: **{r['budgetPassed']}**. The requested reserve is measured against the inherited 145-draw total ceiling. No claim of future Phase C performance is inferred from that reserve.", '', 'Every completed race recorded the following fault counts (events, not Hz samples):','', '| Run | Impacts | Missed gates | Recoveries | Console errors |','|---|---:|---:|---:|---:|']
for x in runs[:4]:lines.append(f"| {x['directory']} | {x['impacts']} | {x['missedGates']} | {x['recoveries']} | {len(x['errors'])} |")
lines+=['', 'Whole-lap Deluge-minus-trench differences: '+', '.join(f'{v:.3f} s' for v in r['forkLapSavingsSeconds'])+' (`reconcile-revision.mjs`). These include traffic and boost. The separately rerun isolated fork timings are in `driving.json`, from `scripts/measure-ascension-driving.mjs`; neither measure is substituted for the other.','', '## Sample reconciliation','', '`reconcile-revision.mjs` computes expected samples as window seconds × calibrated rate. The residual is observed minus expected; render residuals are not missing physics steps. Every retained attempt is included in `reconciliation.json`. Audio and atmosphere lack exported first/last control timestamps, so their residuals against the race window are disclosed rather than claimed to prove exact cadence. Conditional event counters have no fixed expected Hz.','', '| Run / window | Seconds × Hz | Expected | Observed | Residual |','|---|---:|---:|---:|---:|']
for x in runs:
 for label in ['activeRender','tailRender','physics','rivalUpdates','audioControlsAgainstRaceWindow','atmosphereAgainstRaceWindow']:
  s=x[label];lines.append(f"| {x['directory']} / {label} | {s['windowSeconds']:.6f} × {s['expectedRateHz']:.6f} | {s['expected']:.3f} | {s['observed']} | {s['residual']:+.3f} |")
lines+=['', 'Isolated fork savings (`scripts/measure-ascension-driving.mjs`): '+', '.join(f'{v:.3f} s' for v in driving['forkSavingSeconds'])+'. Its 120 Hz simulation sample windows reconcile as follows:']
for sample in driving['sampleReconciliation']:
 expected=sample['windowSeconds']*sample['expectedRateHz'];lines.append(f"- Branch {sample['branch']}: {sample['windowSeconds']:.3f} s × {sample['expectedRateHz']} Hz = {expected:.0f} expected, {sample['observedSamples']} observed, residual {sample['observedSamples']-expected:+.3f}.")
lines+=['', '## Painted road-luma base and pins','', 'Recorded by `record-road-base.py` before `pin-road-floor.py`, both using `frame-metrics.py`. Discrete sector patches, not a temporal sampling window.','', '| Sector | Base luma | Pinned floor |','|---|---:|---:|']
for floor in floors['floors']:lines.append(f"| {floor['sector']} | {floor['baseLuma']:.6f} | {floor['floor']:.6f} |")
lines+=['', 'The scene schedule continues during the short post-finish coast. `reconciliation.json` separates the captured schedule tick from completed race physics steps. Station images and clearance rays are spatial/discrete samples, not frame-rate windows.','', '## Inferences and open acceptance','', '- The new forms and zone transitions appear more distinct in author inspection. This is not the required source-blind classification. The image-only pack is `blind-review/index.html`; the answer key is stored separately. Mangrove identification, hero-quality wording and all thirteen trench classifications remain pending.','- A no-obstruction static ray result does not certify the moving painted crawler or launch sequence. Full spline/ascent clearance and steam speed readability remain Phase C requirements. No inability to meet them was observed in this static repair, and no success in motion is claimed.','- The four Tideline residuals retain their existing scope: new luma pairs are pinned; device glass/bolts/bases and recessed housings retain prior physical evidence; live CHAIN and unfinished power behavior stay open for the later phases specified in `OPEN-GAPS.md`.','- All unrelated prior gaps remain open, including reference/material-ID compliance, missing service job IDs, native sky resolution, other focal assets, device cradles, activation/pasted-on/at-speed evidence, effects/audio, and missing archive validation. See `OPEN-GAPS.md`.','', 'Route/schedule equality against approved `2ebd9d5`: '+json.dumps(preserved)+'.','']
(root/'README.md').write_text('\n'.join(lines))
(root/'OPEN-GAPS.md').write_text('# Remaining acceptance and later-phase gaps\n\nThe five repair implementations are submitted, but source-blind mangrove identification, hero-quality review and the corrected thirteen-frame trench classification are pending. The image-only pack is `blind-review/index.html`. No Phase C work has begun.\n\nAll original gaps outside the five requested repairs remain open as written below. Items 1–3 describe the superseded pre-repair build; their revised implementation evidence is in this directory, and their independent visual gates are not declared passed.\n\n'+Path('art/evidence/ascension-v1/phase-b/OPEN-GAPS.md').read_text())
print(json.dumps({'script':'scripts/visual/ascension/report-revision.py','routeAndSchedulePreserved':preserved,'budgetPassed':r['budgetPassed'],'lumaFloors':len(floors['floors'])}))
